on:
  push:

jobs:
  increment-version:
    name: increment package version
    runs-on: ubuntu-latest
    if: "startsWith(github.event.head_commit.message, '[BUMP]')"

    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
      - run: npm install
      - run: |
          npm --no-git-tag-version version patch
          echo "::set-output name=current-version::$(npm run version)"
        id: vars
      - name: test
        run: echo ${{ steps.vars.currentVersion }}
      - name: Bump Version Commit
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: 'Bump to ${{steps.vars.current-version}}'
          tag: 'v${{steps.vars.current-version}}'
