on:
  push:

jobs:
  increment-version:
    name: increment package version
    runs-on: ubuntu-latest
    if: "startsWith(github.event.head_commit.message, '[BUMP]')"

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup Node
        uses: actions/setup-node@v2
      - name: Increment and Set Version Variable
        id: vars
        run: |
          npm version patch
          npm run version
          echo ::set-output currentVersion={npm run version}
