on:
  push:

jobs:
  increment-version:
    name: increment package version
    runs-on: ubuntu-latest
    if: "startsWith(github.event.head_commit.message, '[BUMP]')"

    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        id: vars
      - run: npm install
      - run: npm test
      - run: |
          npm version patch
          npm run version
          echo ::set-output currentVersion={npm run version}
      - name: Bump Version
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: Bump to ${{steps.vars.currentVersion}}
          tag: v${{steps.vars.currentVersion}}
